baseURL = "https://kaatha-kamrater.se/"
title = "Kååtha Kamrater"

languageCode = "sv-se"
DefaultContentLanguage = "se"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
enableInlineShortcodes = true

[params]
author = "Kååtha Kamrater"
authorimage = "../assets/images/global/author.webp"
instagram = "https://instagram.com/kaathakamrater"
facebook = "https://www.facebook.com/kaathakamrater"
og_image = "/favicon/cover.png"
sitename = "Kååtha Kamrater"
description = "Blekinges styggaste kvasiförening och även kända som omoralens väktare. Arrangerar Kinky Night i månadsskiftet september/oktober eller oktober/november, tror vi. Ingen minns exakt vad som händer, bara att det var en spektakulär fest."

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.104.0"
